# Generated by Django 4.2.4 on 2023-09-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_clinic_address_alter_clinic_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='twitter',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
