# Generated by Django 4.2.4 on 2023-09-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_openingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingtime',
            name='clinic',
            field=models.ManyToManyField(related_name='time_opening', to='clinic.clinic'),
        ),
    ]
