# Generated by Django 4.2.4 on 2023-09-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_service_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maindesc', models.CharField(default='', max_length=255)),
                ('firstdesc', models.CharField(blank=True, max_length=255, null=True)),
                ('seconddesc', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='images/about')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='clinic.clinic')),
            ],
        ),
    ]
