# Generated by Django 4.2.4 on 2023-09-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='offer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clinic',
            name='offer_desc',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
