# Generated by Django 4.2.4 on 2023-09-06 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_clinic_offer_clinic_offer_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=600)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='clinic.clinic')),
            ],
        ),
    ]
