# Generated by Django 4.2.4 on 2023-09-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_alter_testimonial_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='client_image',
            field=models.ImageField(default='./defaultClientPic.png', upload_to='images/clients'),
        ),
    ]
